# hack/Dockerfile.update-codegen

# Usage: docker buildx build --file hack/Dockerfile.update-codegen -o . .

FROM golang:1.13 AS build
WORKDIR /go/src/github.com/viveksinghggits/kluster
RUN go mod download k8s.io/code-generator@v0.21.3
COPY . .
RUN bash /go/pkg/mod/k8s.io/code-generator@v0.21.3/generate-groups.sh all \
    github.com/viveksinghggits/kluster/pkg/client github.com/viveksinghggits/kluster/pkg/apis viveksingh.dev:v1alpha1 \
    --go-header-file /go/pkg/mod/k8s.io/code-generator@v0.21.3/hack/boilerplate.go.txt

FROM scratch
COPY --from=build /go/src/github.com/viveksinghggits/kluster/pkg pkg
